#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

DESTDIR = Debug
CONFIG += debug

DEFINES += 
LIBS += 
INCLUDEPATH += ../../../../../../SysGCC/beaglebone/arm-linux-gnueabihf/sysroot/usr/include/arm-linux-gnueabihf/qt5/QtBluetooth ../../../../../../SysGCC/beaglebone/arm-linux-gnueabihf/sysroot/usr/include/arm-linux-gnueabihf/qt5/QtSql ../../../../Downloads/1.tar/1/lib
QMAKE_LFLAGS += 
QMAKE_CXXFLAGS += -std=gnu++14 -ggdb 
QMAKE_CFLAGS += -std=gnu++14 -ggdb 
